# INPUTS
#
# These are "magically" injected from Github Actions
#
# imageTag: (Mandatory) Tag to pull
# environment: (Mandatory) Which environment to deploy to, must be one of: ["staging", "prod"]

name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

# Triggered directly by Github Actions
trigger: none

variables:
  - name: imageNameNexus
    value: 'nexus.ssb.no:8437/artifact-registry-5n/dapla-stat-docker/jupyter/onprem-jupyterlab'
  - name: imageTag
    value: NOT_SET
  - name: environment
    value: NOT_SET

jobs:
  - job: deploy_staging
    condition: ${{ eq(environment, 'staging') }}
    pool:
      name: jupyterhub-onprem-staging
      demands:
      - agent.name -equals staging-agent

    displayName: "Deploy to staging"
    steps:
      - script: |
          set -e

          IMAGE=${{ variables.imageNameNexus }}:$(imageTag)
          echo "Pulling $IMAGE"
          docker pull $IMAGE

          echo "Removing dangling images"
          docker image prune --force

  - job: deploy_prod
    condition: ${{ eq(environment, 'prod') }}
    pool:
      name: jupyterhub-onprem-prod
      demands:
      - agent.name -equals prod-agent

    displayName: "Deploy to prod"
    steps:
      - script: |
          set -e

          IMAGE=${{ variables.imageNameNexus }}:$(imageTag)
          echo "Pulling $IMAGE"
          docker pull $IMAGE

          echo "Removing dangling images"
          docker image prune --force
