name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

# Triggered directly by Github Actions
trigger: none

variables:
  - name: imageNameNexus
    value: 'nexus.ssb.no:8439/artifact-registry-5n/dapla-stat-docker/jupyter/onprem-jupyterlab'
  - name: imageTag
    value: latest
  - name: environment

jobs:
  - job: deploy-staging
    condition: ${{ eq(variables.environment, 'staging') }}
    pool:
      name: jupyterhub-onprem-staging
      demands:
      - agent.name -equals staging-agent

    displayName: "Deploy to staging"
    steps:
      - script: |
          set -e

          IMAGE=${{ variables.imageNameNexus }}:${{ variables.imageTag }}
          echo "Pulling $IMAGE"
          docker pull $IMAGE

          echo "Removing dangling images"
          docker image prune --force

  - job: deploy-prod
    condition: ${{ eq(variables.environment, 'prod') }}
    pool:
      name: jupyterhub-onprem-prod
      demands:
      - agent.name -equals prod-agent

    displayName: "Deploy to prod"
    steps:
      - script: |
          set -e

          IMAGE=${{ variables.imageNameNexus }}:${{ variables.imageTag }}
          echo "Pulling $IMAGE"
          docker pull $IMAGE

          echo "Removing dangling images"
          docker image prune --force
